### ISSUE TITLE
Hover styles don't work properly on mobile

### ISSUE THREAD

**Issue by JaimieHemmings** [Alvor1991/Hackathon-Team1#10]
On mobile the hover highlight on the divs doesn't work, it only highlights the div where the touchstart and touchend events happen. Might be easier to just use a media query to limit the hover state to only 768px and above

**Comment by sean-meade** [comment]
Fixed by adapting this answer: https://stackoverflow.com/questions/35634226/javascript-detect-finger-moved-over-a-div

**Comment by JaimieHemmings** [comment]
Confirmed resolved.
