### ISSUE TITLE
At touchend or mouseup, there is a strange abrupt "crack" noise

### ISSUE THREAD

**Issue by JaimieHemmings** [Alvor1991/Hackathon-Team1#8]
Need to see if there is a solution to more elegantly end the noise on touchend/mouseup events

**Comment by JaimieHemmings** [comment]
https://stackoverflow.com/questions/65371169/web-audio-api-clicking-sound-when-stopping-oscillator

Possible resolution

**Comment by sean-meade** [comment]
I still got click with linearRamptToValueAtTime but got it working with exponentialRampToValueAtTime:
https://stackoverflow.com/questions/29378875/how-can-i-avoid-this-clicking-sound-when-i-stop-playing-a-sound

**Comment by JaimieHemmings** [comment]
Ended up resolving with setTargetAtTime
